### PR TITLE
Patch TestLocation2D

### PR DESCRIPTION
**Pull request by javajawa**
- The casts were redundant (this is why this class was found, as that showed up as an error in my IDE)
- I also took the liberty of cleaning up some of the other tests (removed some repeated lines, swapped values to be expected/actual)
- The last commit attempts to re-create what I think you were going for with the casts

### CODE REVIEW

**Comment by sammacbeth** [comment]
Merging this gives compile errors as assertTrue(Object) does not exist. Tbh those tests are superfluous anyway so the last commit could be removed.

**Comment by javajawa** [comment]
This is what I get for trusting Netbean's dynamic compilation...oh, and trusting in my ability to put brackets in the right place.

That error is now fixed in cf306eeb

**Comment by javajawa** [comment]
Hmmm...github doesn't seem to want to pick up that this request branch has had another commit added to it. The branch is updated if you fell like it :)

**Comment by sammacbeth** [comment]
Thanks, merged.

**Pull request closed without merging**
